services:
  - type: web
    name: stuart-main-street-api
    env: node
    plan: starter
    buildCommand: npm install && npm run build:server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: stuart-main-street-db
          property: connectionString
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    rootDir: ./
    buildFilter:
      paths:
        - server/**
        - shared/**
        - package.json
        - package-lock.json
        - tsconfig.json
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, PATCH, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization"

databases:
  - name: stuart-main-street-db
    databaseName: stuart_main_street
    user: stuart_user
    plan: starter
